name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name : install LFS
        run: sudo apt-get install -y git-lfs 
      - name: Set up Git repository
        run: git clone https://github.com/Kakashiiiiy/latex_test.git && cd latex_test
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with: 
          working_directory : Data/
          root_file: latex_2.tex
      - name: Upload PDF 
        uses:  actions/upload-artifact@v1
        with:
          name: data
          path: Data/latex_2.pdf
